title: My Presentations
email: your-email@example.com
description: >-
  A collection of presentations built with Jekyll and Reveal.js.

baseurl: "/talks" # the subpath of your site, this is the repository name incase you are deploying using Github Pages e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  presentations:
    output: true
    permalink: /:collection/:name.html

defaults:
  - scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
      render_with_liquid: true

# Keep standard kramdown
markdown: kramdown

